# Generated by Django 4.0.4 on 2022-04-17 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('Ville', models.CharField(max_length=50)),
                ('postale', models.IntegerField()),
                ('telephone', models.IntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Autoriser_a_exercer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Referent_Benevole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('disponibilite', models.DateField()),
                ('nbres_personnes_suivi', models.IntegerField()),
                ('orientations_vers', models.CharField(max_length=50)),
                ('date_orientation', models.DateField()),
                ('etat_avancement', models.CharField(choices=[('En attente', 'En attente'), ('Traiter', 'Traiter'), ('Refusé', 'Refusé')], max_length=50)),
                ('id_personne', models.ForeignKey(db_column='id_personne', on_delete=django.db.models.deletion.DO_NOTHING, to='AppBenevole.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types_mission', models.CharField(choices=[('Autres', 'Autres'), ('Formation', 'Formation'), ('Traveaux Bâtiments', 'Traveaux Bâtiments'), ('Restauration', 'Restauration'), ('Accompagnement Scolaire', 'Accompagnement Scolaire'), ('Informatique (Web, mobile)', 'Informatique (Web, mobile)'), ('Traveaux Ménages', 'Traveaux Ménage'), ('Distribution (Aliments, vêtements', 'Distribution (Aliments, vêtements'), ('vente, commerce', 'vente, commerce'), ('Resources Humaines', 'Resources Humaines'), ('Organisation, Gestion de projest', 'Organisation, Gestion de projest'), ('Ménages', 'ménages'), ('BTP, Logistique, Sécurité, Transport', 'BTP, Logistique, Sécurité, Transport'), ('Aide a linsertion, Parrainges', 'Aide a linsertion, Parrainges')], max_length=50)),
                ('ville', models.CharField(max_length=50)),
                ('postale', models.IntegerField()),
                ('mots_cles', models.CharField(max_length=50)),
                ('id_personne', models.ForeignKey(db_column='id_personne', on_delete=django.db.models.deletion.DO_NOTHING, to='AppBenevole.personne')),
            ],
        ),
        migrations.CreateModel(
            name='EtablissementAccueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=50)),
                ('postale', models.IntegerField()),
                ('types_activités', models.CharField(max_length=50)),
                ('id_personne', models.ForeignKey(db_column='id_personne', on_delete=django.db.models.deletion.DO_NOTHING, to='AppBenevole.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('id_mission', models.ForeignKey(db_column='id_mission', on_delete=django.db.models.deletion.DO_NOTHING, to='AppBenevole.mission')),
                ('id_personne', models.ForeignKey(db_column='id_personne', on_delete=django.db.models.deletion.DO_NOTHING, to='AppBenevole.personne')),
            ],
        ),
    ]
