# Generated by Django 4.0.4 on 2022-04-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBenevole', '0002_connexions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connexions',
        ),
        migrations.AlterField(
            model_name='etablissementaccueil',
            name='types_activités',
            field=models.CharField(choices=[('Autres', 'Autres'), ('Formation', 'Formation'), ('Traveaux Bâtiments', 'Traveaux Bâtiments'), ('Restauration', 'Restauration'), ('Accompagnement Scolaire', 'Accompagnement Scolaire'), ('Informatique (Web, mobile)', 'Informatique (Web, mobile)'), ('Traveaux Ménages', 'Traveaux Ménage'), ('Distribution (Aliments, vêtements', 'Distribution (Aliments, vêtements'), ('vente, commerce', 'vente, commerce'), ('Resources Humaines', 'Resources Humaines'), ('Organisation, Gestion de projest', 'Organisation, Gestion de projest'), ('Ménages', 'ménages'), ('BTP, Logistique, Sécurité, Transport', 'BTP, Logistique, Sécurité, Transport'), ('Aide a linsertion, Parrainges', 'Aide a linsertion, Parrainges')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personne',
            name='Autoriser_a_exercer',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personne',
            name='Email',
            field=models.EmailField(max_length=100),
        ),
    ]
