# Generated by Django 4.0.4 on 2022-05-02 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppBenevole', '0003_delete_connexions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referent_benevole',
            name='cv',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
