# Generated by Django 4.0.4 on 2022-05-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBenevole', '0004_referent_benevole_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referent_benevole',
            name='cv',
        ),
        migrations.AddField(
            model_name='referent_benevole',
            name='Cv_p',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
